### ISSUE TITLE
no tkinter module on/for PyPy3.6 v7.0.0-alpha - Windows binary (32bit) BETA

### ISSUE THREAD

**Issue by manuelcaeiro** [pypy/pypy.packages#1]
I was looking forward to try  PyPy3.6 v7.0.0-alpha. Yesterday I finally was able to download and make it run on my Windows 7 machine.
Put it on the PATH, installed and updated pip, got it as interpreter to execute on 2 of my IDEs... It ran some Python scripts, but when I tried to run a script with tkinter import/code it failed, with the following message:
UnicodeEncodeError: 'mbcs' codec can't encode characters in position 0--1: mbcs encoding does not support errors='surrogateescape'
os.py, line 800

So, I tried to install tkinter but it failed with the following message:
Collecting tkinter
  Could not find a version that satisfies the requirement tkinter (from versions
:  )
No matching distribution found for tkinter

Today I came here and I couldn't spot the package on your list.
Is there a way to install tkinter on pypy?
Thank you.

**Comment by mattip** [comment]
It should be built in, you cannot pip install tkinter. That error is due to the alpha nature of the release. Please try a [nightly](http://buildbot.pypy.org/nightly/py3.6/pypy-c-jit-latest-win32.zip). Our official issue tracker is [here](https://bitbucket.org/pypy/pypy/issues)
